# Generated by Django 3.1.7 on 2021-03-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('no_matter', 'No matter')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex_looking_for',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('no_matter', 'No matter')], default='female', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(max_length=7000),
        ),
    ]
