# Generated by Django 3.1.7 on 2021-03-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210331_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='place_looking_for',
            field=models.CharField(choices=[('city', 'My city'), ('country', 'My country'), ('word', 'All word')], default='city', max_length=10),
        ),
    ]
