# Generated by Django 3.1.7 on 2021-04-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210401_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='match_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
