# Generated by Django 3.1.7 on 2021-04-01 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210401_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationships',
            field=models.ManyToManyField(through='profiles.Relationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
