# Generated by Django 3.1.7 on 2021-04-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210429_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.RemoveField(
            model_name='message',
            name='dialog',
        ),
        migrations.DeleteModel(
            name='Dialog',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
