# Generated by Django 3.1.7 on 2021-05-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
