# Generated by Django 3.1.7 on 2021-05-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chat_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='slug',
        ),
    ]
